language: objective-c
script:
  - xctool -workspace MarvelBrowser.xcworkspace -scheme MarvelBrowser -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace MarvelBrowser.xcworkspace -scheme MarvelBrowser -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
